multistep/commonsteps/http_config.go

fix: `Unable to use http_interface with Proxmox provider hashicorp/packer#10369`

---

plugin/set.go

This is a sister PR to one in the packer core repo to make multiplugin sets capable of using a "default" plugin. This string constant will allow users to register a single specialized plugin that uses the root name of a plugin rather than a compound name. 
For example, if I have a plugin named "packer-plugin-comment", I can register the plugin using the name "foo" in that plugin's main.go: 
```go
pps.RegisterProvisioner("foo", new(CommentProvisioner))
```
and invoke the plugin in my packer template using `"type": "comment-foo"`
If I want, I can use this string constant instead to register the plugin:
```go 
pps.RegisterProvisioner(plugin.DEFAULT_NAME, new(CommentProvisioner))
```
By registering the plugin using this string constant instead of "foo"; this will allow me to invoke the plugin …

add default name constant

---

acctest/datasources.go

This contains a very similar logic to the provisioner acceptance tests.

Add data source acc tests structure

---

template/interpolate/aws/secretsmanager/secretsmanager.go
template/interpolate/aws/secretsmanager/secretsmanager_test.go

Resolves issues [packer issue 10421](https://github.com/hashicorp/packer/issues/10421).
Not sure long term if this GetSecretValue should be converted to return an interface instead of a string, but that would be a large scale refactor. Please let me know if there's anything I should update.

Updated get secret value to handle getting numbers as secrets

---

README.md
scripts/release/release.sh
version/version.go

* Move release documentation to internal documentation walk-through
* Update release script to work with new version.go variables

Update release scripts

---

acctest/pluginacc.go

This generic plugin acceptance test is exactly the same used for data sources but with a generic name so that can be used for all plugins. The idea is to be config language agnostic since it will write a file with the given content and extension and run `packer build` against it. 
The result would be like the acceptance tests added to https://github.com/hashicorp/packer-plugin-scaffolding/pull/6 using this structure.

Add generic plugin acc test

---

packer/ui_mock.go

Update for tests on Paused provisionor required on [this PR](https://github.com/hashicorp/packer/pull/10521). **NOTE** this must be merged first before main PR for packer. 
Part of resolving [packer issue 9691](https://github.com/hashicorp/packer/issues/9691)

Update mock ui to support test case for update on time remaining on

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_requests.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md
CODEOWNERS

This adds some GitHub configuration to set issue's template, pull request's template, and also add contributing documentation and CODEOWNERS to automatically add the packer team as a reviewer. 
The templates were copied and pasted from https://github.com/hashicorp/packer with some adjustments.

Add GitHub config

---

go.mod
go.sum
rpc/client.go
rpc/server.go

This is a continuation of hashicorp/packer#10146 that was submitted before the rpc code was moved from packer to packer-plugin-sdk.
When running Packer built with modern[0] version of ugorji using a plugin built from source and therefore with the 2015 version currently pinned in Packer's go.mod, I hit ugorji/go#269 when my plugin tries to [pipe into a remote "cat > '%s'"](https://github.com/angdraug/packer-builder-nspawn-debootstrap/blob/master/builder/communicator.go#L33):
>  Build 'base-20201021-5f90bdf5-490e-582b-fb1d-b5d4315f5eaa' errored after 25 seconds 772 milliseconds: msgpack decode error [pos 274]: invalid length of bytes for decoding time - expecting 4 or 8 or 12, got 15
[0] As in, newer than ugorji/go@5a66da2 from 2017, e.g. Packer as packaged in Debian.
The same pipe works …

Update ugorji/go/codec to v1.2.4

---

go.mod
go.sum
version/version.go

In case no version is set, we assume this is dev version and defaults to `0.0.0`

Add default version

---

README.md

Docs have been recently updated so previous links in readme went to 404

Update links to documentation

---

didyoumean/name_suggestion.go
go.mod
multistep/commonsteps/http_config.go
multistep/commonsteps/step_http_server.go
multistep/commonsteps/step_http_server_test.go
website/content/partials/multistep/commonsteps/HTTPConfig-not-required.mdx

`HTTPConfig `: Add http_content to be served

---

acctest/pluginacc.go

This adds the `packer init` command to the acceptance test framework.

Add packer init to PluginTestCase

---

bootcommand/pc_xt_driver.go
bootcommand/pc_xt_driver_test.go
bootcommand/vnc_driver.go
bootcommand/vnc_driver_test.go

When typing an upper case character, the scancode for the base key is wrapped with the make/break codes for "Left Shift" (`2a/aa`). For example, typing the letter "N" (`31/f0`) would use the scancode `2a 31 f0 aa`.
This PR fixes an issue with the last two scancodes when typing a character that requires shift. Currently, the last two scancodes are inverted, e.g. `2a 31 aa f0`. This results in Left Shift being released _prior_ to the base key's break code.
I noticed this issue while trying to debug the `prltype.py` script used for typing the boot command in the Parallels builder with macOS VMs (another PR to come). Problems caused by this early `aa` scancode seem more prominent on macOS guests—it may be due to worse guest VM performance. For example, I would often see a colon in the boot …

Fix shift break code order for PC XT and VNC drivers

---

.circleci/config.yml
scripts/release/release.sh

As part of rotating the GPG key used for signing products, we are also moving the GPG bits into a dedicated CircleCI context.  This PR renames the GPG env vars to match those from the new context and applies the context to the job that uses the key.
This was tested locally by modifying the `release.sh` script to not push commits, setting the environment variables to match my local keyring, running the script, and inspecting the produced commit with `git log -n 1 --show-signature`

Update GPG usage

---

go.mod
go.sum
multistep/commonsteps/step_download.go

After tagging the go-getter v2.0.0, a breaking change that happened in the v2 branch makes sdk builds fail as in #64.

Update go-getter to use version 2.0.0

---

multistep/commonsteps/step_create_cdrom.go
multistep/commonsteps/step_create_cdrom_test.go

This adds more robust tests that check the actual filenames and contents in the temporary directory, as well as removing the temporary directory in the step cleanup. This also tests adding folders, which wasn't previously being tested. 
The motivation for checking the content is to allow tests for #61 that test how `cd_files` and `cd_content` interact (e.g. that `cd_content` correctly takes precedence over `cd_files`).

StepCreateCD: Clean up temporary directory and add more robust tests

---

cmd/packer-sdc/internal/renderdocs/docs-partials/packer-plugin-sdk/multistep/commonsteps/CDConfig-not-required.mdx
multistep/commonsteps/extra_iso_config.go
multistep/commonsteps/step_create_cdrom.go
multistep/commonsteps/step_create_cdrom_test.go

Implement `cd_content` from hashicorp/packer#10859, allowing file templating similar to `http_content`.
There currently aren't any tests for this feature. I'd like to first make the `cd_files` tests more robust (at the moment they only test that there are the expected number of keys in `filesAdded`), and then add tests for `cd_content` (including when used alongside `cd_files`).

CDConfig: Add cd_content for file templating

---

communicator/step_connect.go
communicator/step_ssh_keygen.go

👋 Hello! I noticed some parts of the Packer build output that seemed inconsistent or used a weird capitalization. For example: "ssh" instead of "SSH", or "rsa" instead of "RSA". This PR introduces some capitalization changes to the user-facing CLI output to fix those cases.
These capitalizations are arguably really not _necessary_. Maybe this could even break assumptions for users that would want to parse Packer build output? Not totally sure. But, I figured I'd open a PR to get feedback. 😄

Capitalize some parts of the output

---

packer/cache.go
pathing/config_file.go

Addressing last comment from @azr on [previous pr](https://github.com/hashicorp/packer-plugin-sdk/pull/68) before it got merged to update comments to be more accurate and fix issues in comments. @azr Please let me know if there is anything else I should update with these comments. 
Addresses: [hashicorp/packer#9007](https://github.com/hashicorp/packer/issues/9007)

Updating comments for cache and config directories to be accurate

---

cmd/packer-sdc/internal/renderdocs/docs-partials/packer-plugin-sdk/provisioners/common-config.mdx
cmd/packer-sdc/internal/renderdocs/docs-partials/packer-plugin-sdk/provisioners/community_provisioners.mdx
cmd/packer-sdc/internal/renderdocs/docs-partials/packer-plugin-sdk/provisioners/shell-config.mdx
cmd/packer-sdc/internal/renderdocs/docs-partials/packer-plugin-sdk/provisioners/unmaintained-plugin.mdx

So that we can generate partial docs for inspec and salt provisioners

import provisioner partials from Packer core

---

multistep/commonsteps/step_download.go

Stores the iso url that was actually used, in case there were several options. This will be useful for tracking image provenance in the HCP Packer registry, for iso builds. I need this information in the vsphere iso builder.

store source image url that was actually used, for recordkeeping

---

cmd/packer-sdc/internal/plugincheck/README.md
cmd/packer-sdc/internal/plugincheck/cmd.go

Before change
```
~>  packer-sdc plugin-check packer-plugin-puppet
2021/11/11 14:06:49 this plugin defines no component.
```
After Change
```
~>   packer-sdc plugin-check packer-plugin-puppet && echo $?
0
```

Fix plugin-check cmd for provisioner only plugins

---

cmd/packer-sdc/internal/struct-markdown/struct_markdown.go
cmd/packer-sdc/internal/struct-markdown/struct_markdown_test.go

This pull request fixes #104 by forcing the file path in the files generated by packer-sdc to use forward slashes regardless of the OS where packer-sdc is used.

Fix file path in comments for windows

---

CHANGELOG.md
multistep/commonsteps/step_download.go

* Disable reading and writing files through symlinks
* Add timeouts for GCS and S3 getters
Related to: https://github.com/hashicorp/packer-internal-issues/issues/38 (internal only)

Update go-getter client options

---

multistep/commonsteps/step_create_cdrom_test.go

A little change that was found during setting up the project on Windows.
The tests were relying on unix paths "/" while on Windows we have "\"
and tests were failing in checkFiles with the such messages as:
unexpected file: subfolder\meta-data

Change step_create_cdrom_tests to pass on Windows

---

.circleci/config.yml

Support for Xcode 12.0.0 has been deprecated on CircleCI. This change
updates the build configuration to use the latest stable Xcode version
available.

Update Xcode version for Darwin test builds

---

communicator/sshkey/generate.go

As said in the method comment, the method produced the key in a format incompatible with ssh. As a result, the key Packer SDK created resulted in the error `Load key "id_ed25519": invalid format`.
I found the [format description ](https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.key) and fixed the generation algorithm to fix this problem:
- I added proper padding generation
- and put the public key in the right place as described in the format.
As `ed25519` keys are getting more popular, I think it would be helpful to have them serialize correctly.

Make ed25519 keys generated by Packer serialize in the format usable by ssh

---

cmd/packer-sdc/internal/renderdocs/docs-partials/packer-plugin-sdk/communicator/SSH-not-required.mdx
communicator/config.go

Fix small typo in the comment for an SSH configuration option where algorithm was misspelled.

communicator: fix SSH config typo

---

multistep/commonsteps/step_create_cdrom.go
multistep/commonsteps/step_create_cdrom_test.go

Packer recommends that we use "/" as the path separator. There is a
problem with using it on Windows with nested folders because of the following behaviour:
We might pass paths with forward slashes in `StepCreateCD` struct
The string `rootFolder, err := tmp.Dir("packer_to_cdrom")` makes rootFolder use system-based slashes, which is "\\" for Windows.
This rootFolder is passed to `s.AddFile(rootFolder, toAdd)`
And a mix of two slashes ruins our replace logic while going through the `visit` function. We end up having different slashes for `allDirs` and `discardPath` in `intermediaryDirs := strings.Replace(allDirs, discardPath, "", 1)`
We change our replace login to don't depend on slashes.
The tests we had didn't cover such cases as we passed all files with paths constructed with …

Fix possibility to use forward slashes with nested folders in cd_files for Windows

---

communicator/sshkey/pubkey.go
communicator/sshkey/pubkey_test.go
communicator/step_ssh_keygen.go

Provision SSHPublicKey while use custom SSH Private key

---

cmd/packer-sdc/internal/renderdocs/docs-partials/packer-plugin-sdk/communicator/WinRM-not-required.mdx
cmd/packer-sdc/internal/renderdocs/docs-partials/packer-plugin-sdk/multistep/commonsteps/FloppyConfig.mdx
communicator/config.go
multistep/commonsteps/floppy_config.go

Links are redirecting to the wrong page on the new website.

Update docs links

---

sdk-internals/communicator/ssh/communicator.go

We used to check if a ssh server returns an empty payload with a len(fi) < 0, which can never succeed as len never returns negative values.
This commit changes the condition to an == instead.

ssh: fix DownloadDir empty response check

---

bootcommand/config.go
cmd/packer-sdc/internal/renderdocs/docs-partials/packer-plugin-sdk/bootcommand/BootConfig.mdx
cmd/packer-sdc/internal/renderdocs/docs-partials/packer-plugin-sdk/communicator/SSH-not-required.mdx
cmd/packer-sdc/internal/renderdocs/docs-partials/packer-plugin-sdk/multistep/commonsteps/FloppyConfig.mdx
communicator/config.go
multistep/commonsteps/floppy_config.go

- Migrates the formats of links in Markdown content as part of the [Docs
Content Link Rewrites
project](https://docs.google.com/document/d/1WaSyvoVPS-YCNiSPX0ynGpvc1gySEcpbrRoQVhimQCA/edit)

Update links used in embedded documentation partials

---

shell-local/config.go

Commit 34ed5d9031 which consists of linting fixes essentially had an error in the code and the error check for `supported_os' was inverted in this commit, making shell-local fail on all supported OSes now.
We re-invert this condition so it behaves as it used to.

shell-local: fix supported_os error check

---

cmd/packer-sdc/internal/mapstructure-to-hcl2/mapstructure-to-hcl2.go
cmd/packer-sdc/internal/mapstructure-to-hcl2/mapstructure-to-hcl2_test.go
cmd/packer-sdc/internal/test-data/field-conflict/test_mapstructure_field_conflict.go
cmd/packer-sdc/internal/test-data/tag-conflict/test_mapstructure_tag_conflict.go

When generating the flattened structures for a HCL2-compatible config, we didn't prevent users from defining duplicate fields or tags, instead warning them.
The warning in itself did not prevent the resulting structures from being generated, leading into a situation where the first definition of the arg/tag would have precedence over the subsequent definitions, leading to shadowing their definitions.
To prevent this in the future, we immediately return an error when such a conflict is introduced, and signal to the user which attribute is problematic.
Related to: https://github.com/hashicorp/packer-plugin-alicloud/pull/107
Related to: https://github.com/hashicorp/packer-plugin-alicloud/pull/105

packer-sdc: return errors on duplicate tag/field

---

.github/workflows/actionlint.yml
.github/workflows/go-test.yml
.github/workflows/release.yml

As part of the ongoing efforts to migrate from Circle CI to GHA, this PR pins the external actions to a SHA, adds actionlint to the repo, and fixes permissions for actions that didn't have it yet.

GHA migration finalisation

---

rpc/common.go
rpc/common_test.go
rpc/datasource_test.go

The Packer SDK relies on encoding/gob for serializing hcldec.ObjectSpec over RPC. The added test check that types implementing the HCL2Speccer interface can be encoded/decoded without issue.
Starting in go-cty v1.11.0 support for encoding/gob was removed, which causes the added tests to fail. This is expected and is meant to help catch potential regressions moving forward.
Test results running go-cty v1.10.0
--- PASS: TestCommonServer_ConfigSpec (0.00s)
--- PASS: TestCommonServer_ConfigSpec/Builder_Component_Server (0.00s)
--- PASS: TestCommonServer_ConfigSpec/Datasource_Component_Server (0.00s)
--- PASS: TestCommonServer_ConfigSpec/Provisioner_Component_Server (0.00s)
=== RUN   TestCommunicatorRPC
Test results running go-cty v1.13.1
```
~> go get github.com/zclconf/go-cty@v1.13.1
~>  go …
```

[HPR-1100] Add basic test for commonServer.ConfigSpec

---

communicator/config.go
communicator/config_test.go

When attempting to set the bastion key/certificate for authenticating with the bastion, we generally fallback to the ones defined by the SSH configuration.
However, if the bastion SSH key is set, and not the certificate, but the SSH connection's are, since the conditions are separate, we end-up in a situation where the bastion's SSH key uses the one from the config, and the certificate fall backs to the one from the SSH connection.
This in turn fails, as the certificate's public key matches the private key from the SSH connection, and not the bastion's.
To avoid a situation like this, we only fallback to the SSH connection's certificate if the bastion's SSH key isn't set.
Closes #173

communicator: don't set bastion cert if key is set

---

filelock/filelock.go
go.mod
go.sum
multistep/commonsteps/iso_config_test.go
packer/cache_config_unix.go
packer/cache_config_unix_test.go
packer/cache_config_windows.go
packer/cache_config_windows_test.go
pathing/config_file_unix.go
pathing/config_file_unix_test.go
pathing/config_file_windows.go
pathing/config_file_windows_test.go
sdk-internals/communicator/ssh/communicator_test.go
template/parse_test.go

In an effort to provide Packer plugins access to the github.com/zclconf/go-cty enhancements, while still providing access to encoding/gob support the Packer team has forked the go-cty package under github.com/nywilken/go-cty. 
This is a temporary fork that will be removed once it is no longer needed.
* This change also reverts the Go statement to 1.18 in the go.mod file. The SDK has no dependencies on Go 1.20 to justify the Go version bump in the module file.
Relates to: https://github.com/hashicorp/packer-plugin-sdk/issues/187

[HPR-1108] Replace gitub.com/zclconf/go-cty@1.12.1 with fork github.com/nywilken/go-cty

---

cmd/packer-sdc/internal/renderdocs/docs-partials/packer-plugin-sdk/multistep/commonsteps/HTTPConfig.mdx
multistep/commonsteps/http_config.go

Problem: HTTP server example usage is shown with backticks [in the documentation](https://developer.hashicorp.com/packer/plugins/builders/tart#http-server-configuration) ([source includes `packer-plugin-sdk/multistep/commonsteps/HTTPConfig.mdx`](https://github.com/cirruslabs/packer-plugin-tart/blob/c5e6e6f40fafb0fc033e5048fd706721d7fe2869/docs/builders/tart.mdx#L61)):
Solution: explicitly treat example usage as code.

Remove extra backticks from HTTP server documentation

---

.github/workflows/go-test.yml
cmd/packer-sdc/internal/fix/cmd.go
go.mod

- Remove use of Go 1.20 language features
- Add matrix builds for supported Go versions
Branched from #197

packer-sdc: Remove version specific Go code

---

acctest/pluginacc.go

When running an acceptance test, we may need to invoke Packer with extra flags to ensure it behaves as expected.
Therefore, we add this capability to the TestCase structure so it injects them verbatim in the command-line.

acctest: add capability to add args to build

---

hcl2helper/values.go

When the code from a plugin differs from its generated FlatConfig, we may encounter a nil object spec for the values in the output of a component.
This translates as a nil dereferencing panic within the hcl library, caused by a config and tags being out-of-sync.
To avoid users the hassle of delving in this code, and the hcl library's, we preemptively panic in the SDK code, with a message suggesting regenerating the code for the component's specs.

hcl2helper: preemptively panic on nil hcl spec

---

cmd/packer-sdc/internal/fix/gocty.go
cmd/packer-sdc/internal/fix/gocty_test.go
cmd/packer-sdc/internal/fix/testdata/fixed/basic/go.mod
cmd/packer-sdc/internal/fix/testdata/fixed/many-replace/go.mod
cmd/packer-sdc/internal/fix/testdata/unfixed/basic/fixed.go.mod
cmd/packer-sdc/internal/fix/testdata/unfixed/many-replace/fixed.go.mod
cmd/packer-sdc/internal/fix/testdata/unfixed/version/fixed.go.mod
cmd/packer-sdc/internal/fix/testdata/unfixed/version/go.mod
go.mod
go.sum

This change updates the supported versions for go-cty and hcl/v2. To assist plugin developers, including the Packer team, support the plugin ecosystem the packer-sdc fix command has been updated
to add, or updating applied fixes, for the go-cty fork to version 1.13.3. 
- Update go-cty fixer replace directive to github.com/nywilken/go-cty v1.13.3
- Bump github.com/zclconf/go-cty to v1.13.3
- Bump github.com/hashicorp/hcl/v2 to v1.19.1
Related to: #187 
Related to: #188

Bump supported version of go-cty to v1.13.3

---

plugin/set_test.go
version/version.go
version/version_test.go

As it stands now, plugin developers can only specify a version's core semver-compatible version, and a prerelease.
In usage though, some plugins use metadata to add some extra context on the binary that was built, like the git commit, or the delta between the last release and the current HEAD from which a plugin was built. 
This, coupled with the 1.11.0 changes to plugin loading and version support, means that we cannot support such a workflow with the current code, as we will now start enforcing proper semver for plugins, so we are at risk of having plugins either not load, or lose information when releasing.
Therefore as an attempt to address those issues, we are adding official support in the SDK for metadata in versions. That change introduces two new functions: `NewPluginVersion` and …

Version parsing rehaul

---

.github/workflows/actionlint.yml
.github/workflows/go-test.yml
.github/workflows/release.yml

```shell
tsccr-helper gha update -latest .
```

Update all tsccr approved actions

---

Makefile
communicator/sshkey/algorithm_enumer.go

Since the enumer implementation we used hadn't been updated for 5+ years, this didn't work with recent linux/go versions, and enumer crashed while attempting to parse/analyse the source files.
There's another alternative on Github, forked from the one we used, which seems more maintained now, and does produce the expected files in the SDK.

Makefile: replace enumer upstream with dmarkham's

---

cmd/packer-sdc/internal/renderdocs/docs-partials/packer-plugin-sdk/communicator/SSH-not-required.mdx
communicator/config.go

As pointed out in [a Packer PR](https://github.com/hashicorp/packer/pull/12949), the option's name does not match its real name for the ssh file transfer method.
This commit fixes that mismatch.

communicator: fix reference to ssh_method in docs

---

communicator/step_connect_ssh.go
communicator/step_connect_winrm.go
multistep/commonsteps/step_provision_test.go
net/configure_port.go
sdk-internals/communicator/winrm/communicator.go

When joining an ipv6 host and a port, the host must be wrapped between brackets, otherwise the port will become part of the host.
Closes #245

Fix ipv6 addresses format

---

go.mod
go.sum

- Bump google.golang.org/protobuf@v1.33.0
- Bump github.com/hashicorp/vault/api@1.14.0

Bump dependencies to address govulncheck reported vulnerabilities

---

.goreleaser.yml

```
~>  goreleaser -v
GitVersion:    2.0.1
~>  goreleaser check
• checking                                 path=.goreleaser.yml
• 1 configuration file(s) validated
• thanks for using goreleaser!
```

.goreleaser.yml: Update configuration to v2

---

plugin/set.go
plugin/set_test.go

This change refactors the logic inside of parseProtobufFlag to handle the case where multiple `--protobuf` flags are specified, while removing unnecessary guard clauses. 
In addition to the refactor tests were added to validate the behavior before and after the reactor
```
~>  go test ./plugin/... -v
=== RUN   TestPluginServerRandom
--- PASS: TestPluginServerRandom (0.00s)
=== RUN   TestSet
--- PASS: TestSet (0.00s)
=== RUN   TestSetProtobufArgParsing
=== RUN   TestSetProtobufArgParsing/no_--protobuf_argument_provided
=== RUN   TestSetProtobufArgParsing/providing_--protobuf_as_first_argument
=== RUN   TestSetProtobufArgParsing/providing_--protobuf_as_last_argument
=== RUN   TestSetProtobufArgParsing/providing_--protobuf_as_middle_argument
=== RUN …
```

plugin/set.go: Add test for validation protobuf flag parsing

---

template/funcs.go
template/interpolate/aws/secretsmanager/secretsmanager.go
template/interpolate/aws/secretsmanager/secretsmanager_test.go
template/interpolate/funcs.go

Hi Packer community!
This PR solves the issue described in [Packer Issue ](https://github.com/hashicorp/packer/issues/13112). Currently, the secret manager is only able to work with simple `key:value` pairs in JSON format. This is unfortunate as there are other types of secrets in the world.
In this PR, I have added an additional argument to secretsmanager, which allows you to select whether you want the secret in raw/plain form or in the default `key:value` pair format.
Essentially, the only change is that the `awsmanager` function `GetSecret()` now takes one additional argument `raw`, which is a simple boolean. This boolean instructs the function to return the plain string value of the secret even if the secret is valid JSON.
There are two tests implemented for this feature. If you are …

Support raw/plain secret pull from AWS Secret Manager

---

multistep/commonsteps/step_download.go
multistep/commonsteps/step_download_test.go

Should now be overridable via the environment variable `PACKER_GETTER_READ_TIMEOUT`

commonsteps: StepDownload timeout override

---

go.mod
go.sum

Since v4.0.1 of the go-jose module is vulnerable to CVE-2025-22868, we bump to v4.0.5 to remediate this.
Note: while the dependency is vulnerable to this CVE, the attack is not realistic for Packer, hence this was not a problem in the first place, but bumping the dependency to make scanners happy.

go.mod: bump go-jose to 4.0.5

---

cmd/packer-sdc/internal/renderdocs/docs-partials/packer-plugin-sdk/communicator/SSH-not-required.mdx
communicator/config.go

Added missing documentation for the ssh_remote_tunnels and ssh_local_tunnels flags.

Added Documentaion Comments for SSH Tunnel flags

---

multistep/doc.go

Updated the `doc.go` file to adhere to [Go Doc Comment](https://go.dev/doc/comment) syntax. This allows the documentation to render correctly on `pkg.go.dev`.
I was reading the `multistep` package documentation when I noticed this. Perhaps there are more packages that need updating but I didn't enumerate them.

multistep: use go doc comment syntax

---

acctest/provisioneracc/test-fixtures/amazon-ebs/amazon-ebs_windows.txt
go.mod

Changing the path here to reference it to the bootstrap_win.txt file thats been added here (https://github.com/hashicorp/packer/pull/13334)
Currently i believe the acceptance tests fail with "user_data_file" not found.
Also adding skip_create_ami to not create an AMI when running acceptance tests

fixes for packer_acc_tests for windows 

---

packer/ui.go
packer/ui_mock.go
rpc/ui.go
rpc/ui_test.go

Deprecating the `Message` method from the cli UI interface to simplify the logs and replacing them with the Say method.

Deprecating `Message` method in UI interface
